# Generated by Django 4.2 on 2024-05-22 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "brand_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Brand ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Brand name")),
            ],
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "vehicle_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Vehicle ID"
                    ),
                ),
                (
                    "vehicle_model",
                    models.CharField(max_length=200, verbose_name="Vehicle model"),
                ),
                (
                    "license_plate",
                    models.CharField(max_length=20, verbose_name="License Plate"),
                ),
                ("year", models.IntegerField(verbose_name="Year")),
                (
                    "transmission",
                    models.CharField(
                        choices=[("Automatic", "Automatic"), ("Manual", "Manual")],
                        verbose_name="Transmission",
                    ),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("Gasoline", "Gasoline"),
                            ("Diesel", "Diesel"),
                            ("Alcohol", "Alcohol"),
                        ],
                        verbose_name="Fuel type",
                    ),
                ),
                (
                    "number_of_doors",
                    models.IntegerField(verbose_name="Number of doors"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        height_field=300,
                        null=True,
                        upload_to="upload/%d/%m/%Y/",
                        verbose_name="Vehicle image",
                        width_field=300,
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vehicle_brand",
                        related_query_name="brand",
                        to="cars.brand",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="brand",
            index=models.Index(fields=["brand_id", "name"], name="brand_id_name_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="brand",
            unique_together={("brand_id", "name")},
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(fields=["vehicle_model", "year"], name="model_year_idx"),
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(fields=["year", "brand"], name="year_brand_idx"),
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(
                fields=["vehicle_model", "year", "brand"], name="model_year_brand_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(
                fields=["year", "brand", "fuel_type"], name="year_brand_fueltype_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(
                fields=["year", "transmission", "fuel_type"],
                name="year_transmission_fueltype_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="vehicle",
            constraint=models.CheckConstraint(
                check=models.Q(("year__gte", 1920)), name="year_gte_1920"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="vehicle",
            unique_together={("vehicle_model", "year")},
        ),
    ]
